project:
  type: book
execute:
  freeze: auto

book:
  title: "Awesome thesis"
  author: "Bob Hette"
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
    - "refs.qmd"
  appendices:
    - App-A.qmd
    - App-B.qmd
# Info for website page (footer and navbar)    
  page-footer:
    left: |
      By Bob Hette.
    right: |
      This thesis was built with <a href="https://quarto.org/">Quarto</a>.
  reader-mode: true
  search: true
  repo-url: https://github.com/yourcaccount/thesis/
  downloads: [pdf]
  navbar:
    background: light
    collapse-below: lg
    title: "PhD Thesis B. Hette"


# Thesis information
degreetype: Doctor of Philosophy
submitted: 2024
affiliation: Department of Biology
degrees: 'M.Sc., University of Blablabla'

# Bibliography style information
bibliography: [biblio/thesisrefs.bib, biblio/_packages.bib]
csl: biblio/american-statistical-association.csl


# Output format
format:
  biouOthesis-html:
    cover-image: figures/cover.png
  biouOthesis-pdf: default