# this sets the directory that your output gets stored in
# Putting it in a 'docs' folder is convenient if you want to publish HTML
# output with GitHub Pages 
output_dir: "docs"

# If the below is set to true, you don't have to manually delete the merged 
# _main.qmd file if something goes wrong when you try to build
delete_merged_file: true

# By default, bookdown will automatically merge .qmd files in the root folder
# into your thesis. If you specify a sub directory with qmd_subdir, bookdown
# searches through this folder too. .qmd files you don't want automatically
# included, should start with an underscore, e.g. _abstract.qmd (otherwise 
# bookdown would merge the abstract into the body text)
qmd_subdir: ["front-and-back-matter"]

# You can override bookdown's automatic merging of files, and explicitly
# specify files to include with "qmd_files" like this:
#qmd_files: ["index.qmd", "00-introduction.qmd", "01-how-to-use.qmd", "07-conclusion.qmd", "front-and-back-matter/98-appendices.qmd", "front-and-back-matter/99-references_heading.qmd"]

# If you want people to be able to suggest and submit changes to the source .qmd
# files on your github repo, do it like so (https://bookdown.org/yihui/bookdown/html.html)
edit: https://github.com/ulyngs/bio_uO_down/tree/master/%s